# Generated by Django 6.1.1 on 2026-10-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
