# Generated by Django 6.1.1 on 2026-10-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
