# Generated by Django 6.1.1 on 2026-10-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_interviewsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='resume',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='resume.interviewsession'),
        ),
    ]
