# Generated by Django 6.1.1 on 2026-10-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_interviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='improvements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
